name: Deploy to Github Pages

on:
   push:
      branches: [backup]

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
   contents: read
   pages: write # to deploy to Pages
   id-token: write # to verify the deployment originates from an appropriate source

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      env:
         REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

      steps:
         - name: Checkout Source
           uses: actions/checkout@v4
         - name: Setup Node
           uses: actions/setup-node@v4
           with:
              node-version: 20
         - name: Install Dependencies
           run: npm ci
         - name: Build Project
           run: npm run build
         - name: Upload artifacts
           uses: actions/upload-pages-artifact@v3
           with:
              name: "github-pages"
              path: build
         - name: Deploy to Github Pages
           uses: actions/deploy-pages@v4
           with:
              token: ${{ secrets.GITHUB_TOKEN }}
              artifact_name: "github-pages"
